# Generated by Django 5.2.8 on 2025-11-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnails',
            field=models.ImageField(blank=True, null=True, upload_to='product_thumbnail/'),
        ),
    ]
